server:
  port: 8089
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
      - id: leave-service
        uri: lb://LEAVE-SERVICE
        predicates:
        - Path=/api/leave
