spring:
  threads:
    virtual:
      enabled: true
  cloud.gateway.mvc:
    routesMap:
      configRoute1:
        uri: lb://leave-service
        predicates:
          - Path=/api/leave/*
      configRoute2:
        id: discovery-server
        uri: http://localhost:8761/
        predicates:
          - Path=/eureka/web
      configRoute3:
        id: employee-service
        uri: lb://employee-service
        predicates:
          - Path=/api/employee/*



#      configRoute3:
#        uri: lb://httpbin
#        predicates:
#          - Path=/anything/configroute3
#        filters:
#          - AddRequestHeader=X-Test,configRoute3
logging:
  level:
    org.springframework.cloud.gateway.server.mvc: TRACE
    org.springframework.web: TRACE
management:
  endpoints:
    web:
      exposure:
        include: '*'